import SiteNav from '@/components/SiteNav'
import '../assets/css/main.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import SiteHeader from '@/components/SiteHeader'
import SiteFooter from '@/components/SiteFooter'
import { AuthProvider } from './AuthProvider'
const inter = Inter({ subsets: ['latin'] })
import {registerLicense} from '@syncfusion/ej2-base'

const license = process.env.SYNCF;
registerLicense(license as string)

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SiteHeader />
          <main>{children}</main>
          <SiteFooter />
        </AuthProvider>
      </body>
    </html>
  )
}
